spring:
  application:
    name: mv-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaozaoshun/mv-config/
          search-paths: /
          username: 739178184@qq.com
          password: 13556457068+qq
          #配置为true表示启动时就克隆配置缓存到本地。
          clone-on-start: true
          #配置为true表示如果本地副本是脏的，将使Spring Cloud Config Server强制从远程存储库拉取配置。
          force-pull: true
      label: master
  rabbitmq:
    host: 192.168.66.128
    port: 5672
    username: admin
    password: 123456
server:
  port: 10011
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:10001/eureka/
management:
  security:
    enabled: false