spring:
  application:
    name: mv-consumer-feign
server:
  port: 10005
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:10001/eureka/
feign:
  hystrix:
    enabled: true