spring:
  application:
    name: mv-provider-basic
  zipkin:
    service:
      name: mv-zipkin
server:
  port: 10033
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:10001/eureka/